logging:
  level:
    com.rodtech.qideasregisterapi.client.AuthClient: DEBUG
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
